#:kivy 2.0
<Field>:
    background_down:''
    background_normal:''

<HomeSheet>:
    BoxLayout:
        orientation: 'vertical'
        GridLayout:
            id: maze
            cols: 30
            rows: 25
            spacing: .5

        BoxLayout:
            id: footer
            orientation: 'horizontal'
            size_hint: (1.0, .05)
            Button:
                text: "Solve"
                
            Button:
                text: "Properties"

